### ISSUE TITLE
Base files

### ISSUE THREAD

**Issue by Cheekygrays** [zuri-training/Team-Shark2W_metadata_#10]

**Comment by digitaltomer** [comment]
Done the base files for backend and the frontend can also add their files also

**Comment by digitaltomer** [comment]
![Screenshot 2022-12-05 at 5 31 19 PM](https://user-images.githubusercontent.com/20678556/205692999-d05b1049-8f3c-4121-946f-ce779f9fc503.png)

**Comment by Cheekygrays** [comment]
Great
